    fields:
    - caption: Installation type
      type: list
      name: inst_type
      default: poc
      values:
        poc: PoC
        sb: Sandbox
        prod: Production
        high_prod: High Performance Production
      showIf:
        poc:
          - caption: RAM&CPU Infra
            name: infra_cpu_ram
            required: true
            values: infraFlavorListPrepared
            type: list
            tooltip: 
              text: "<h2>PoC Installation Type</h2>Make sure the Flavor meets the requirements for <b>Infra</b> nodes. <a href='https://www.virtuozzo.com/application-platform-ops-docs/hardware-requirements-local-storage/'>Learn More</a><p></p> <img width='600' height='250' src='https://raw.githubusercontent.com/sych74/vap-installer/main/images/poc-requirements.svg'>"
              tipParams:
              maxWidth: 830
              minWidth: 300
          - caption: RAM&CPU User
            name: user_cpu_ram
            required: true
            values: userFlavorListPrepared
            type: list
            tooltip: 
              text: "<h2>PoC Installation Type</h2>Make sure the Flavor meets the requirements for <b>User</b> nodes. <a href='https://www.virtuozzo.com/application-platform-ops-docs/hardware-requirements-local-storage/'>Learn More</a><p></p> <img width='600' height='250' src='https://raw.githubusercontent.com/sych74/vap-installer/main/images/poc-requirements.svg'>"
              tipParams:
              maxWidth: 830
              minWidth: 300
        sb:
          - caption: RAM&CPU Infra
            name: infra_cpu_ram
            required: true
            values: infraFlavorListPrepared
            type: list
            tooltip: 
              text: "<h2>Sandbox Installation Type</h2>Make sure the Flavor meets the requirements for <b>Infra</b> nodes. <a href='https://www.virtuozzo.com/application-platform-ops-docs/hardware-requirements-local-storage/'>Learn More</a><p></p> <img width='600' height='250' src='https://raw.githubusercontent.com/sych74/vap-installer/main/images/sandbox-requirements.svg'>"
              tipParams:
              maxWidth: 830
              minWidth: 300
          - caption: RAM&CPU User
            name: user_cpu_ram
            required: true
            values: userFlavorListPrepared
            type: list
            tooltip: 
              text: "<h2>Sandbox Installation Type</h2>Make sure the Flavor meets the requirements for <b>User</b> nodes. <a href='https://www.virtuozzo.com/application-platform-ops-docs/hardware-requirements-local-storage/'>Learn More</a><p></p> <img width='600' height='250' src='https://raw.githubusercontent.com/sych74/vap-installer/main/images/sandbox-requirements.svg'>"
              tipParams:
              maxWidth: 830
              minWidth: 300
        prod:
          - caption: RAM&CPU Infra
            name: infra_cpu_ram
            required: true
            values: infraFlavorListPrepared
            type: list
            tooltip: 
              text: " <h2>Production Installation Type</h2>Make sure the Flavor meets the requirements for <b>Infra</b> nodes. <a href='https://www.virtuozzo.com/application-platform-ops-docs/hardware-requirements-local-storage/'>Learn More</a><p></p> <img width='600' height='250' src='https://raw.githubusercontent.com/vlobzakov/vap-installer/main/images/performance-requirements.svg'>"
              tipParams:
              maxWidth: 830
              minWidth: 300
          - caption: RAM&CPU User
            name: user_cpu_ram
            required: true
            values: userFlavorListPrepared
            type: list
            tooltip: 
              text: " <h2>Production Installation Type</h2>Make sure the Flavor meets the requirements for <b>User</b> nodes. <a href='https://www.virtuozzo.com/application-platform-ops-docs/hardware-requirements-local-storage/'>Learn More</a><p></p> <img width='600' height='250' src='https://raw.githubusercontent.com/vlobzakov/vap-installer/main/images/performance-requirements.svg'>"
              tipParams:
              maxWidth: 830
              minWidth: 300
        high_prod:
          - caption: RAM&CPU Infra
            name: infra_cpu_ram
            required: true
            values: infraFlavorListPrepared
            type: list
            tooltip: 
              text: "<h2>High Performance Production Installation Type</h2>Make sure the Flavor meets the requirements for <b>Infra</b> nodes. <a href='https://www.virtuozzo.com/application-platform-ops-docs/hardware-requirements-local-storage/'>Learn More</a><p></p> <img width='600' height='250' src='https://raw.githubusercontent.com/vlobzakov/vap-installer/main/images/high-performance-requirements.svg'>"
              tipParams:
              maxWidth: 830
              minWidth: 300
          - caption: RAM&CPU User
            name: user_cpu_ram
            required: true
            values: userFlavorListPrepared
            type: list
            tooltip: 
              text: "<h2>High Performance Production Installation Type</h2>Make sure the Flavor meets the requirements for <b>User</b> nodes. <a href='https://www.virtuozzo.com/application-platform-ops-docs/hardware-requirements-local-storage/'>Learn More</a><p></p> <img width='600' height='250' src='https://raw.githubusercontent.com/vlobzakov/vap-installer/main/images/high-performance-requirements.svg'>"
              tipParams:
              maxWidth: 830
              minWidth: 300

    - caption: VAP Stack Name
      type: string
      tooltip: VAP Stack Name
      name: vap_stack_name
      required: true
      value: vapStackName

    - type: compositefield
      caption: Infra OS/Vz Data, GB
      defaultMargins: "0 12 0 0"
      tooltip:
        text: "Storage volume size for '<b>/</b>' and '<b>/vz</b>' partition for Infra nodes"
        minWidth: 370        
      items:
        - type: spinner
          name: infra_os_storage_size
          min: 100
          max: 2000
        - type: displayfield
          markup: "/"
          cls: x-form-item-label
          width: 10
        - type: spinner
          name: infra_vz_storage_size
          min: 400
          max: 5000

    - type: compositefield
      caption: User OS/Vz Data, GB
      defaultMargins: "0 12 0 0"
      tooltip:
        text: "Storage volume size for '<b>/</b>' and '<b>/vz</b>' partition for User nodes"
        minWidth: 370        
      items:
        - type: spinner
          name: user_os_storage_size
          min: 100
          max: 2000
        - type: displayfield
          markup: "/"
          cls: x-form-item-label
          width: 10
        - type: spinner
          name: user_vz_storage_size
          min: 400
          max: 5000

    - caption: User Node Count
      type: spinner
      tooltip: User Node Count
      name: user_node_count
      min: 1
      max: 5

    - caption: VHI Public Subnet
      type: list
      tooltip: "Select required VHI cluster subnet"
      name: subnet
      required: true
      values: subnetListPrepared

    - caption: VAP Image Name
      type: list
      tooltip: Select required qcow2 VAP image name
      name: image_name
      required: true
      values: imageListPrepared
